# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-12 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True, max_length=100, null=True, verbose_name='头像地址')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='昵称')),
                ('is_admin', models.BooleanField(default=False, verbose_name='超级用户')),
                ('identity', models.CharField(blank=True, choices=[('normal', 'normal'), ('author', 'author')], max_length=10, null=True, verbose_name='身份')),
                ('belong_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
