# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-19 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.URLField(blank=True, default='website/static/images/hou30.jpg', max_length=100, null=True, verbose_name='头像地址'),
        ),
    ]
